set quiet # Recipes are silent by default

init:
    terraform -chdir=modules/aws_infra init
    # terraform -chdir=modules/kubernetes_infra init
    terraform -chdir=modules/cos_aws init
apply: init apply_aws_infra apply_cos
destroy: destroy_cos destroy_aws_infra

apply_aws_infra:
    @echo "Applying AWS resources..."
    terraform -chdir=modules/aws_infra apply -var="region=eu-central-1"

# apply_k8s_infra:
#     @echo "Applying Kubernetes resources..."
#     terraform -chdir=modules/kubernetes_infra apply \
#         -var="host=$(terraform -chdir=modules/aws_infra output -raw eks-host)" \
#         -var="token=$(terraform -chdir=modules/aws_infra output -raw eks-token)" \
#         -var="ca=$(terraform -chdir=modules/aws_infra output -raw eks-ca-certificate)" \
#         -var="aws_region=eu-central-1"

apply_cos:
    @echo "Applying COS resources..."
    terraform -chdir=modules/cos_aws apply \
        -var="loki_bucket=$(terraform -chdir=modules/aws_infra output -raw loki-bucket)" \
        -var="tempo_bucket=$(terraform -chdir=modules/aws_infra output -raw tempo-bucket)" \
        -var="mimir_bucket=$(terraform -chdir=modules/aws_infra output -raw mimir-bucket)" \
        -var="s3_endpoint=$(terraform -chdir=modules/aws_infra output -raw s3-endpoint)" \
        -var="s3_user=$(terraform -chdir=modules/aws_infra output -raw s3-user)" \
        -var="s3_password=$(terraform -chdir=modules/aws_infra output -raw s3-password)" \
        -var="model=$(terraform -chdir=modules/aws_infra output -raw model)" \

# -var="controller_addresses=$(terraform -chdir=modules/kubernetes_infra output -raw controller-public-address)" \
# -var="controller_user=$(terraform -chdir=modules/aws_infra output -raw controller-username)" \
# -var="controller_password=$(terraform -chdir=modules/aws_infra output -raw controller-password)" \
# -var="controller_ca=$(terraform -chdir=modules/aws_infra output -raw controller-ca)" \
# -var="client_host_address=$(terraform -chdir=modules/aws_infra output -raw management-instance-host)" \

destroy_cos:
    @echo "Destroying COS resources..." 
    terraform -chdir=modules/cos_aws destroy \
        -var="loki_bucket=$(terraform -chdir=modules/aws_infra output -raw loki-bucket)" \
        -var="tempo_bucket=$(terraform -chdir=modules/aws_infra output -raw tempo-bucket)" \
        -var="mimir_bucket=$(terraform -chdir=modules/aws_infra output -raw mimir-bucket)" \
        -var="s3_endpoint=$(terraform -chdir=modules/aws_infra output -raw s3-endpoint)" \
        -var="s3_user=$(terraform -chdir=modules/aws_infra output -raw s3-user)" \
        -var="s3_password=$(terraform -chdir=modules/aws_infra output -raw s3-password)" \
        -var="model=$(terraform -chdir=modules/aws_infra output -raw model)" \

destroy_aws_infra:
   @echo "Destroying AWS resources..." 
   terraform -chdir=modules/aws_infra destroy 

# destroy_k8s_infra:
#    @echo "Destroying Kubernetes resources..." 
#    terraform -chdir=modules/kubernetes_infra destroy 
