name: 'Task Runner'
description: 'Run tests for a charm'
inputs:
  charm-path:
    description: 'Path to the charm'
    required: true
  test-type:
    description: 'Test type (e.g., lint, fmt, static, etc.)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run test
      shell: bash
      run: |
        cd ${{ inputs.charm-path }}
        if [ -f tox.ini ]; then  # Run Tox
          tox -vve ${{ inputs.test-type }}
        elif [ -f Makefile ]; then  # Run Make
          if grep -q -E "^\s*${{ inputs.test-type }}:" Makefile; then
            make ${{ inputs.test-type }}
          else
            echo "Error: Invalid Make target (${{ inputs.test-type }})."
            exit 1
          fi
        else
          echo "Error: Taskrunner file not found."
          exit 1
        fi