set quiet # Recipes are silent by default

init:
    terraform init
    terraform -chdir=../cos init

apply: init apply_infra apply_cos

destroy: destroy_cos destroy_infra

apply_infra:
    terraform apply

apply_cos:
    terraform -chdir=../cos apply -var-file=../cos/aws.tfvars \
        -var="loki_bucket=$(terraform output -raw loki-bucket)" \
        -var="tempo_bucket=$(terraform output -raw tempo-bucket)" \
        -var="mimir_bucket=$(terraform output -raw mimir-bucket)" \
        -var="s3_endpoint=$(terraform output -raw s3-endpoint)" \
        -var="s3_user=$(terraform output -raw s3-user)" \
        -var="s3_password=$(terraform output -raw s3-password)" \

destroy_infra:
   terraform destroy

destroy_cos:
    terraform -chdir=../cos destroy var-file=../cos/aws.tfvars \
        -var="loki_bucket=$(terraform output -raw loki-bucket)" \
        -var="tempo_bucket=$(terraform output -raw tempo-bucket)" \
        -var="mimir_bucket=$(terraform output -raw mimir-bucket)" \
        -var="s3_endpoint=$(terraform output -raw s3-endpoint)" \
        -var="s3_user=$(terraform output -raw s3-user)" \
        -var="s3_password=$(terraform output -raw s3-password)" \
