name: Promote Train

on:
  schedule:
    - cron: '0 11 * * 2'
  workflow_dispatch:

jobs:
  promote:
    name: Promote Charm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        charm:
          # Observability Core
          - alertmanager-k8s
          - avalanche-k8s
          - blackbox-exporter
          - blackbox-exporter-k8s
          - catalogue-k8s
          - cos-configuration-k8s
          - cos-proxy
          - grafana-k8s
          - loki-coordinator-k8s
          - loki-k8s
          - loki-worker-k8s
          - mimir-coordinator-k8s
          - mimir-worker-k8s
          - opentelemetry-collector
          - opentelemetry-collector-k8s
          - otelcol-integrator
          - prometheus-k8s
          - prometheus-pushgateway-k8s
          - prometheus-scrape-config-k8s
          - prometheus-scrape-target-k8s
          - script-exporter
          - snmp-exporter

          # Tracing & Profiling
          - k6-k8s
          - litmus-auth-k8s
          - litmus-backend-k8s
          - litmus-chaoscenter-k8s
          - litmus-infrastructure-k8s
          - otel-ebpf-profiler
          - parca-agent
          - parca-k8s
          - parca-scrape-target
          - polar-signals-cloud-integrator
          - pyroscope-coordinator-k8s
          - pyroscope-worker-k8s
          - tempo-coordinator-k8s
          - tempo-worker-k8s

          # Service Mesh
          - grafana-agent
          - grafana-agent-k8s
          - grafana-cloud-integrator
          - istio-beacon-k8s
          - istio-ingress-k8s
          - istio-k8s
          - kiali-k8s
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo snap install just --classic
          sudo snap install charmcraft --classic
          sudo snap install juju --classic

      - name: Promote charm
        env:
          CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
        run: just promote-train ${{ matrix.charm }}

