name: Static Analysis

on:
  workflow_call:
    inputs:
      charm-path:
        type: string
        required: false

jobs:
  static-lib:
    name: Static Analysis of Libs
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis for /lib for 3.8
        run: cd ${{ inputs.charm-path }} && tox -vve static-lib
  static-charm:
    name: Static Analysis of Charm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python3 -m pip install tox
      - name: Run static analysis (charm)
        run: cd ${{ inputs.charm-path }} && tox -vve static-charm
