name: Bundle Pull Request

on:
  workflow_call:
    inputs:
      bundle-path:
        description: "Path to the bundle we want to publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string
      provider:
        description: "The provider to choose for either machine or k8s tests ('lxd' or 'microk8s')"
        default: 'microk8s'
        required: false
        type: string
      ip-range:
        type: string
        description: |
          The IP range in the address pool for the load balancer to use.
          It can be either a subnet(IP/mask) or a range (<IP1>-<IP2>)
        required: false
        default: null
    secrets:
       CHARMHUB_TOKEN:
         required: false
jobs:
  ci-ignore:
    name: Check against ignorelist
    runs-on: ubuntu-latest
    outputs:
      any_modified: ${{ steps.echo-changes.outputs.any_modified }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }} # To be compatible with PRs from forks
          fetch-depth: 0

      - name: Determine changed files in the PR
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          files_ignore: |
            README.md
            CONTRIBUTING.md
            INTEGRATING.md
            CODEOWNERS
            LICENSE
            icon.svg
            .gitignore
            .github/**

      - name: Echo changed files
        id: echo-changes
        run: |
          echo "Changes made: ${{ steps.changed-files.outputs.any_modified }}"
          echo "Modified files: ${{ steps.changed-files.outputs.all_modified_files }}"
          echo "any_modified=${{ steps.changed-files.outputs.any_modified }}" >> $GITHUB_OUTPUT

  codeql:
    name: CodeQL analysis
    needs:
      - ci-ignore
    if: needs.ci-ignore.outputs.any_modified == 'true'
    uses: canonical/observability/.github/workflows/_charm-codeql-analysis.yml@main
    with:
      charm-path: "${{ inputs.bundle-path }}"

  linting:
    name: Linting
    needs:
      - ci-ignore
    if: needs.ci-ignore.outputs.any_modified == 'true'
    uses: canonical/observability/.github/workflows/_charm-linting.yaml@main
    with:
      charm-path: "${{ inputs.bundle-path }}"

  integration-test:
    name: Integration Tests
    needs:
      - ci-ignore
      - codeql
      - linting
    if: needs.ci-ignore.outputs.any_modified == 'true'
    uses: canonical/observability/.github/workflows/_charm-tests-integration.yaml@main
    with:
      charm-path: "${{ inputs.bundle-path }}"
      provider: "${{ inputs.provider }}"
      ip-range: ${{ inputs.ip-range }}
