name: Release Bundle

on:
  workflow_call:
    
jobs:
    per-channel-integration-matrix:
        name: Per-channel integration matrix
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                charm-channel: [ "edge", "beta", "candidate", "stable" ]
        steps:
        -   name: Run integration matrix for ${{ matrix.charm-channel }} channel
            uses:  canonical/observability/.github/workflows/_bundle_release.yaml@main
            with:
                charm-channel: ${{ matrix.charm-channel }}

