name: Security vulnerability scan - charms

on:
    workflow_dispatch:
    schedule:
      - cron: "0 1 * * 1"  # Runs at 1am UTC every Monday

jobs:
    scan:
        name: Security vulnerability scan
        runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          - name: Checkout security scanner
            uses: actions/checkout@v4
            with:
              repository: canonical/sbomber
              path: scanner
              token: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
          - name: Install juju
            run: | 
              sudo snap install juju --classic
          - name: Install secscan cli
            run: |
              sudo snap install canonical-secscan-client
              sudo snap connect canonical-secscan-client:home system:home
          - name: Install uv
            run: |
              sudo snap install astral-uv --classic
          - name: Prepare the artifacts
            run: |
              cd scanner
              ./sbomber prepare ../manifests/charm-security-scan.yaml
          - name: Submit the artifacts
            run: |
              cd scanner
              ./sbomber submit
          - name: Wait for the scans to finish
            run: |
              cd scanner
              ./sbomber poll --wait --timeout 30
          - name: Download the reports
            run: |
              cd scanner && ./sbomber download
          - name: Upload reports
            uses: actions/upload-artifact@v4
            with:
              name: secscan-report-upload
              path: ./scanner/reports/*.html
