# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

# Usage documentation: static-code-analysis.md

name: Security vulnerability scan

on:
  workflow_dispatch:
    inputs:
      charm-name:
        type: string
        required: true
        description: |
          The charm we want to be scanned.
      charm-channel:
        type: string
        default: "latest/edge"
        required: false
        description: |
          The channel from which to download the charm.
  workflow_call:
    inputs:
      charm-name:
        type: string
        required: true
        description: |
          The charm we want to be scanned.
      charm-channel:
        type: string
        default: "latest/edge"
        required: false
        description: |
          The channel from which to download the charm.

jobs:
  pack:
    name: Fetch the charm
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Install juju
        id: install
        run: |
          sudo snap install juju
      - name: Download the charm
        id: download-charm
        run: |
          juju download ${{ inputs.charm-name }} --channel ${{ inputs.charm-channel }}
      - name: Store charm(s)
        uses: actions/upload-artifact@v4
        with:
          name: charms-amd64
          path: ./*.charm
  scan:
    name: Run the security scan
    needs:
      - pack
    uses: canonical/observability/.github/workflows/_secscan.yaml@feat/secscan
    with:
      artifacts-type: package
      artifacts-format: charm
      artifacts-key: charms-amd64
      artifact-path: ${{ inputs.charm-path }}/*.charm
