name: Release Libraries

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm whose libraries we want to publish."
        default: '.'
        required: false
        type: string
    secrets:
      CHARMHUB_TOKEN:
        required: true
      OBSERVABILITY_NOCTUA_TOKEN:
        required: true

jobs:
  release-libs:
    name: Release any bumped library
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Release any bumped charm library
        uses: canonical/charming-actions/release-libraries@main
        with:
          charm-path: "${{ inputs.charm-path }}"
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}"

