name: SBOM generation - charms

on:
    workflow_dispatch:
#    pull_request:
    schedule:
      - cron: "0 1 * * 1"  # Runs at 1am UTC every Monday

jobs:
    scan:
        strategy:
          fail-fast: false
          matrix:
            manifest: [sbom, secscan]
        name: SSDLC artifact scanning - charms
        runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
        steps:
          - name: Run sbomber
            uses: canonical/sbomber/.github/workflows/run-scanner.yaml@feat/reusable-workflow
            with:
              manifests-pattern: ../ssdlc-manifests/charm-sbom.yaml
              self-hosted-runner: self-hosted-linux-amd64-jammy-private-endpoint-medium
