name: Release Charm

on:
  workflow_call:
    inputs:
      charm-path:
        description: "Path to the charm we want to publish. Defaults to the current working directory."
        default: '.'
        required: false
        type: string
      artifact:
        description: "Name of artifact to download before building. Must contain the file artifact.tar.gz."
        default: ''
        required: false
        type: string
      provider:
        description: "The provider to choose for either machine or k8s tests ('lxd' or 'microk8s')"
        default: 'microk8s'
        required: false
        type: string
    secrets:
      CHARMHUB_TOKEN:
        required: true

concurrency:
  group: release
  cancel-in-progress: true

jobs:
  quality-checks:
    uses: canonical/observability/.github/workflows/_quality-checks.yaml@main
    secrets: inherit
    with:
      charm-path: "${{ inputs.charm-path }}"
      provider: "${{ inputs.provider }}"
  release-charm:
    needs: 
      - quality-checks
    uses: ./.github/workflows/_charm-release.yaml
    secrets: inherit
    with:
      artifact: "${{ inputs.artifact }}"
      charm-path: "${{ inputs.charm-path }}"
