name: Build rock and release dev tag to GHCR

on:
  workflow_call:
    inputs:
      rock-path:
        description: "Optional path to the rock(s) directory to operate in"
        required: false
        default: "."
        type: string
    secrets:
      OBSERVABILITY_NOCTUA_TOKEN:
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo snap install concierge --classic
        sudo concierge prepare -p crafts --extra-snaps=just,yq,syft
    - name: Build rock and release to GHCR
      id: build-and-release
      env:
        GITHUB_TOKEN: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
      run: |
        cd "${{ inputs.rock-path }}"
        echo "latest_version=$(just latest-version)" >> "$GITHUB_ENV"
        just pack
        just release-ghcr
    - name: Create SBOM
      id: create-sbom
      run: |
        cd "${{ inputs.rock-path }}"
        just sbom
        echo rock_name="$(just name)" >> "$GITHUB_OUTPUT"
    - name: Upload SBOM
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.create-sbom.outputs.rock_name }}-rock-sbom
        path: "${{ inputs.rock-path }}/${{ steps.build-and-release.outputs.latest_version }}/rock.sbom.json"
    - name: Upload locally built rock artifact
      uses: actions/upload-artifact@v4
      with:
        name: dev.rock
        path: "${{ inputs.rock-path }}/${{ steps.build-and-release.outputs.latest_version }}/*.rock"
