name: Pull Request

on:
  workflow_call:
    inputs:
      rock-path:
        description: "Optional path to the rock(s) directory to operate in"
        required: false
        default: "."
        type: string


jobs:
  changes:
    name: Determine modified rocks
    runs-on: ubuntu-24.04
    outputs:
      versions: ${{ steps.changed-versions.outputs.versions }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Find rockcraft.yaml changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          path: ${{ inputs.rock-path }}
          files: "**/rockcraft.yaml"
      - name: Extract the versions
        id: changed-versions
        env:
          ROCK_PATH: ${{ inputs.rock-path }}
          # CHANGED_FILES is a space-separated list
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          raw_versions="${CHANGED_FILES//\/rockcraft.yaml/}"  # space-separated versions
          versions=""
          for raw_path in $raw_versions; do
            version="${raw_path#*$ROCK_PATH/}"  # Remove 'rock_path/' and everything before it
            version="${version%%/*}"  # Remove everything after the first '/'
            versions+="$version "
          done
          echo "versions=$versions"
          echo "versions=$versions" >> "$GITHUB_OUTPUT"

  tests:
    name: Tests
    runs-on: ubuntu-24.04
    needs: [changes]
    if: needs.changes.outputs.versions != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install concierge --classic
          sudo concierge prepare -p crafts --extra-snaps=just,yq,docker
      - name: Print disk utilization
        if: ${{ (runner.debug == '1') }}
        run: df -h
      - name: Clean worker caches
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a
      - name: Print disk utilization after cleanup
        if: ${{ (runner.debug == '1') }}
        run: df -h
      - name: Pack and test the rocks
        run: |
          cd "${{ inputs.rock-path }}"
          for version in ${{ needs.changes.outputs.versions }}; do
            just pack "$version"
            just test "$version"
            just clean "$version"
          done
      - name: Print disk utilization after packing
        if: ${{ (runner.debug == '1') }}
        run: df -h
      - name: Open SSH session on failure
        if: ${{ failure() && (runner.debug == '1') }}
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 30
          limit-access-to-actor: true
