name: Run a security scan for the rock

on:
  workflow_call:
    inputs:
      rock-name:
        description: "Name of the application for which to build the rock"
        required: true
        type: string

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo snap install concierge --classic
        sudo concierge prepare -p microk8s --extra-snaps=just,yq
    - name: Build rock
      run: |
        latest_version="$(find . -maxdepth 1 -type d -name '[0-9]*' | sort -V | tail -n1 | sed 's@./@@')"
        just pack "$latest_version"
    - name: Upload locally built rock artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.rock-name }}-rock
        path: "./**/${{ inputs.rock-name }}_*.rock"
  scan:
    name: Run the security scan
    needs:
      - pack
    uses: canonical/observability/.github/workflows/_secscan.yaml@feat/secscan
    with:
      artifacts-type: container-image
      artifacts-format: oci
      artifacts-key: ${{ inputs.rock-name }}-rock
      artifact-path: "${{ inputs.rock-name }}_*.rock"