name: Open a PR to OCI Factory when a new rock is merged to main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_call:
    inputs:
      rock-path:
        description: "Path to the rock(s) directory to operate in (defaults to 'rock')"
        required: false
        default: "."
        type: string
      rock-support:
        description: "Which level of semantic version to support in the OCI Factory ('patch', 'minor', 'major')"
        required: false
        default: "minor"
        type: string
      risk-track:
        description: "Risk track on which to release the rock"
        required: false
        default: "stable"
        type: string
      
    secrets:
      OBSERVABILITY_NOCTUA_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release-oci-factory:
    name: Add the new rock
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the rock repository
        uses: actions/checkout@v4
        with:
          path: ${{ inputs.rock-path }}
          fetch-depth: 2 # Needed to check modified files
      - name: Find rockcraft.yaml changes
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          path: ${{ inputs.rock-path }}
          files: "**/rockcraft.yaml"
      - name: Extract the versions
        id: changed-versions
        env:
          ROCK_PATH: ${{ inputs.rock-path }}
          # CHANGED_FILES is a space-separated list
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          versions="${CHANGED_FILES//\/rockcraft.yaml/}"  # space-separated versions
          echo "versions=$versions"
          echo "versions=$versions" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        if: steps.changed-files.outputs.all_changed_and_modified_files != ''
        run: |
          sudo snap install just --classic
          sudo snap install astral-uv --classic  # used to run noctua
          sudo snap install yq
      - name: Release to OCI Factory
        if: steps.changed-files.outputs.all_changed_and_modified_files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
        run: |
          for version in $versions; do
            echo "Releasing version $version to OCI Factory on track ${{ inputs.risk-track }}"
            just release-oci-factory "$version" ${{ inputs.rock-support }} ${{ inputs.risk-track }}
          done
