name: Run a security scan for the rock

on:
  workflow_call:
    inputs:
      rock-name:
        description: "Name of the rock"
        required: true
        type: string
      rock-version:
        description: "Version of the rock"
        required: true
        type: string

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - name: Install Docker
      run: |
        sudo snap install docker --classic
    - name: Pull and save the image
      run: |
        sudo docker pull ${{ inputs.rock-name }}:${{ inputs.rock-version }}
        sudo docker download ${{ inputs.rock-name }}:${{ inputs.rock-version }} | gzip -c -9 > ${{ inputs.rock-name }}_${{ inputs.rock-version }}.rock
    - name: Upload locally fetched rock artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.rock-name }}-fetched-rock
        path: "./${{ inputs.rock-name }}_*.rock"
  scan:
    name: Run the security scan
    needs:
      - pack
    uses: canonical/observability/.github/workflows/_secscan.yaml@feat/secscan
    with:
      artifacts-type: container-image
      artifacts-format: oci
      artifacts-key: ${{ inputs.rock-name }}-fetched-rock
      artifact-path: "./${{ inputs.rock-name }}_*.rock"