name: Pull Request

on:
  workflow_call:

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo snap install concierge --classic
          sudo concierge prepare -p crafts --extra-snaps=just,yq
      - name: Run tests
        run: snapcraft test
      - name: Open SSH session on failure
        if: ${{ failure() && (runner.debug == '1') }}
        uses: mxschmitt/action-tmate@v3
        with:
          timeout-minutes: 30
          limit-access-to-actor: true
