name: SSDLC scanning

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 1,15 * *"
#              │ │ │  │    │
#              │ │ │  │    └─ any day of the week.
#              │ │ │  └────── 1st and 15th of every month.
#              │ │ └───────── Any day (covered by day-of-month above).
#              │ └─────────── 0th hour of the day.
#              └───────────── Start of the hour (minutes = 0).

jobs:
    scan:
        runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
        strategy:
          fail-fast: false
          matrix:
            type: [sbom, secscan]
            artifact: [rock, charm]

        name: ${{ matrix.type == 'sbom' && 'SBOM Scan' || 'SecScan' }} (${{ matrix.artifact }}s)
        steps:
          - name: Checkout
            uses: actions/checkout@v6
          - name: Install yq
            run: sudo snap install yq
          - name: Generate manifest
            env:
              SSDLC_MANIFEST_OUTPUT: /tmp/ssdlc-manifest.yaml
            run: just security::generate-ssdlc-manifest ${{ matrix.type }} ${{ matrix.artifact }}
          - name: Run sbomber action
            uses: canonical/sbomber/.github/actions/run@main
            with:
              manifest: /tmp/ssdlc-manifest.yaml
              artifact-name: ${{ matrix.artifact }}-${{ matrix.type }}
