name: SSDLC scanning

on:
    workflow_dispatch:
    schedule:
      - cron: "0 0 22 7 *"
        #      │ │ │ │ │
        #      │ │ │ │ └─ any day of the week.
        #      │ │ │ └─── 7th month (July).
        #      │ │ └───── 22nd day of the month.
        #      │ └─────── 0th hour of the day.
        #      └───────── Start of the hour (minutes = 0).

jobs:
    scan:
        runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]
        strategy:
          fail-fast: false
          matrix:
            type: [sbom, secscan]
            artifact: [rock, charm]

        name: SSDLC scanning - ${{ matrix.type }} - ${{ matrix.artifact }} artifacts
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - name: Run sbomber action
            uses: canonical/sbomber/.github/actions/run
            with:
              manifest: "${{ github.workspace }}/ssdlc-manifests/${{ matrix.artifact }}-${{ matrix.type }}-manifest.yaml"
              artifact-name: ${{ matrix.artifact }}-${{ matrix.type }}