name: Auto-update Charm Libraries
on:
  workflow_call:
    inputs:
      charm-path:
        required: false
    secrets:
      CHARMHUB_TOKEN:
        required: false
      OBSERVABILITY_NOCTUA_TOKEN:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-lib:
    name: Check libraries
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # v3
        with:
          fetch-depth: 0

      - name: Check libs
        run: |
          sudo snap install charmcraft --classic --channel latest/stable
          cd ${{ inputs.charm-path }}
          charmcraft fetch-lib
        env:
          CHARMCRAFT_AUTH: "${{ secrets.CHARMHUB_TOKEN }}"

      - name: Create a PR for local changes
        uses: peter-evans/create-pull-request@v4.2.3
        id: cpr
        with:
          token: ${{ secrets.OBSERVABILITY_NOCTUA_TOKEN }}
          commit-message: "chore: update charm libraries"
          committer: "Github Actions <github-actions@github.com>"
          author: "Github Actions <github-actions@github.com>"
          title: "Update charm libraries"
          body: Automated action to fetch latest version of charm libraries.
          branch: "chore/auto-libs"
          delete-branch: true
